version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-23-92-204.compute-1.amazonaws.com
            database: d5ujlbb49vbq2j
            ssl: true
            user: neluzdxliicayy
            password: 448331d86fffe201ffaea83227ca495df80a945febae24a2176318ab7b3a2ebd
            rawAccess: true
            port: '5432'
            migrations: true
